CREATE TABLE "agent_runtime_profiles" (
	"agent_id" uuid PRIMARY KEY NOT NULL,
	"server_id" uuid NOT NULL,
	"machine_id" uuid NOT NULL,
	"runtime_profile_fingerprint" text NOT NULL,
	"runtime" text NOT NULL,
	"model" text NOT NULL,
	"reasoning_effort" text,
	"execution_mode" text NOT NULL,
	"daemon_version" text,
	"workspace_ref_label" text,
	"workspace_ref_path" text,
	"workspace_ref_machine_id" text,
	"workspace_ref_runtime" text,
	"workspace_ref_reachable" boolean,
	"workspace_ref_reason" text,
	"workspace_path_ref_label" text,
	"workspace_path_ref_path" text,
	"workspace_path_ref_machine_id" text,
	"workspace_path_ref_runtime" text,
	"workspace_path_ref_reachable" boolean,
	"workspace_path_ref_reason" text,
	"session_ref_label" text,
	"session_ref_path" text,
	"session_ref_machine_id" text,
	"session_ref_runtime" text,
	"session_ref_reachable" boolean,
	"session_ref_reason" text,
	"baseline_runtime_profile_fingerprint" text NOT NULL,
	"baseline_machine_id" uuid NOT NULL,
	"baseline_runtime" text NOT NULL,
	"baseline_model" text NOT NULL,
	"baseline_reasoning_effort" text,
	"baseline_execution_mode" text NOT NULL,
	"baseline_daemon_version" text,
	"migration_status" text DEFAULT 'stable' NOT NULL,
	"pending_kind" text,
	"pending_key" text,
	"pending_before_runtime_profile_fingerprint" text,
	"pending_after_runtime_profile_fingerprint" text,
	"pending_before_machine_id" uuid,
	"pending_after_machine_id" uuid,
	"pending_before_runtime" text,
	"pending_after_runtime" text,
	"pending_before_model" text,
	"pending_after_model" text,
	"pending_before_reasoning_effort" text,
	"pending_after_reasoning_effort" text,
	"pending_before_execution_mode" text,
	"pending_after_execution_mode" text,
	"pending_before_daemon_version" text,
	"pending_after_daemon_version" text,
	"pending_previous_session_label" text,
	"pending_previous_session_path" text,
	"pending_previous_session_machine_id" text,
	"pending_previous_session_runtime" text,
	"pending_previous_session_reachable" boolean,
	"pending_previous_session_reason" text,
	"pending_release_notes_url" text,
	"migration_delivered_at" timestamp with time zone,
	"migration_delivered_launch_id" text,
	"migrating_since" timestamp with time zone,
	"last_migration_nudge_at" timestamp with time zone,
	"migration_nudge_count" integer DEFAULT 0 NOT NULL,
	"migration_handled_at" timestamp with time zone,
	"migration_handled_launch_id" text,
	"revision" integer DEFAULT 1 NOT NULL,
	"observed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "agent_runtime_profiles" ADD CONSTRAINT "agent_runtime_profiles_agent_id_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runtime_profiles" ADD CONSTRAINT "agent_runtime_profiles_server_id_servers_id_fk" FOREIGN KEY ("server_id") REFERENCES "public"."servers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runtime_profiles" ADD CONSTRAINT "agent_runtime_profiles_machine_id_daemons_id_fk" FOREIGN KEY ("machine_id") REFERENCES "public"."daemons"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runtime_profiles" ADD CONSTRAINT "agent_runtime_profiles_baseline_machine_id_daemons_id_fk" FOREIGN KEY ("baseline_machine_id") REFERENCES "public"."daemons"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runtime_profiles" ADD CONSTRAINT "agent_runtime_profiles_pending_before_machine_id_daemons_id_fk" FOREIGN KEY ("pending_before_machine_id") REFERENCES "public"."daemons"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_runtime_profiles" ADD CONSTRAINT "agent_runtime_profiles_pending_after_machine_id_daemons_id_fk" FOREIGN KEY ("pending_after_machine_id") REFERENCES "public"."daemons"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_agent_runtime_profiles_server" ON "agent_runtime_profiles" USING btree ("server_id");--> statement-breakpoint
CREATE INDEX "idx_agent_runtime_profiles_machine" ON "agent_runtime_profiles" USING btree ("machine_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idx_agent_runtime_profiles_pending_key" ON "agent_runtime_profiles" USING btree ("pending_key");--> statement-breakpoint
CREATE INDEX "idx_agent_runtime_profiles_pending" ON "agent_runtime_profiles" USING btree ("server_id","updated_at") WHERE pending_kind is not null;
