import type { ApiProxyDiagnostics, ApiResponse } from "../client.js";
import { CliError, type CliErrorCode } from "./errors.js";

type ApiFailure = Pick<ApiResponse<unknown>, "status" | "errorCode" | "suggestedNextAction" | "proxy"> & {
  error?: string | null;
};

export function apiFailureError(
  response: ApiFailure,
  fallbackCode: string,
  options: {
    server5xxCode?: CliErrorCode;
    suggestedNextAction?: string;
  } = {},
): CliError {
  const proxyFailure = response.status >= 500 && response.errorCode === "agent_proxy_failed";
  const code = response.status >= 500
    ? proxyFailure
      ? "PROXY_5XX"
      : (response.errorCode as CliErrorCode | undefined) ?? options.server5xxCode ?? "SERVER_5XX"
    : (response.errorCode as CliErrorCode | undefined) ?? fallbackCode as CliErrorCode;
  return new CliError({
    code,
    message: response.error ?? `HTTP ${response.status}`,
    suggestedNextAction: options.suggestedNextAction
      ?? response.suggestedNextAction
      ?? (proxyFailure
        ? "This 5xx was generated by the local daemon proxy; use the correlation id to inspect daemon proxy transport logs before attributing it to the server."
        : undefined),
    ...proxyCliErrorOptions(response.proxy),
  });
}

export function proxyCliErrorOptions(proxy: ApiProxyDiagnostics | null | undefined): {
  layer?: string;
  correlationId?: string;
  proxyFailureClass?: string;
  proxyCauseCode?: string;
  proxyRouteFamily?: string;
  proxyUpstreamLayer?: string;
  proxyUpstreamStatus?: number;
  proxyResponseStarted?: boolean | null;
  proxyResponseComplete?: boolean | null;
} {
  if (!proxy) return {};
  return {
    layer: proxy.layer ?? undefined,
    correlationId: proxy.correlationId ?? undefined,
    proxyFailureClass: proxy.failureClass ?? undefined,
    proxyCauseCode: proxy.causeCode ?? undefined,
    proxyRouteFamily: proxy.routeFamily ?? undefined,
    proxyUpstreamLayer: proxy.upstreamLayer ?? undefined,
    proxyUpstreamStatus: proxy.upstreamStatus ?? undefined,
    proxyResponseStarted: proxy.responseStarted ?? undefined,
    proxyResponseComplete: proxy.responseComplete ?? undefined,
  };
}
