import type { Brand } from "@botiverse/raft-shared";

import type { CliIo } from "./io.js";
import type { CliError } from "./errors.js";

/**
 * Text that is allowed to be written to the CLI reply face (stdout). Only the
 * axSurface wrapper below mints it (definitions live in the command families'
 * _format.ts modules — gated), so every byte an agent reads
 * from a command reply traces to a registered formatter in the generated
 * ax-surfaces.manifest.json. Counterpart of the daemon's AxSurfaceText.
 */
export type CliReplyText = Brand<string, "CliReplyText">;

export interface AxSurfaceExample<A extends readonly unknown[]> {
  readonly title?: string;
  /** One invocation's arguments, typechecked against the formatter's own parameter tuple. */
  readonly args: A;
}

export interface AxSurfaceOptions<A extends readonly unknown[]> {
  /** REQUIRED and non-empty (@xxchan ruling): a surface without an example does not compile. */
  readonly examples: readonly [AxSurfaceExample<A>, ...AxSurfaceExample<A>[]];
}

export type AxSurfaceMeta<A extends readonly unknown[]> = {
  readonly axDescription: string;
  readonly axExamples: readonly AxSurfaceExample<A>[];
};

/**
 * Define a registered agent-visible CLI reply surface. This wrapper is the
 * ONLY way to produce CliReplyText (besides the pinned adoptCliReplyText
 * escape hatch), so defining a formatter and registering it are the same act:
 * the ax-surfaces manifest is generated by scanning `axSurface(` call sites,
 * and an unwrapped function simply cannot reach writeText/writeDiagnostic.
 * Description AND at least one typed example live in the same expression —
 * there is no second place; the AX HTML renders fn(...example.args) directly
 * via the axExamples attached to the returned function.
 *
 * The description must be a string literal — the manifest generator refuses
 * computed descriptions.
 */
export function axSurface<A extends readonly unknown[]>(
  description: string,
  format: (...args: A) => string,
  options: AxSurfaceOptions<A>,
): ((...args: A) => CliReplyText) & AxSurfaceMeta<A>;
export function axSurface<A extends readonly unknown[]>(
  description: string,
  format: (...args: A) => string | null,
  options: AxSurfaceOptions<A>,
): ((...args: A) => CliReplyText | null) & AxSurfaceMeta<A>;
export function axSurface<A extends readonly unknown[]>(
  description: string,
  format: (...args: A) => string | null,
  options: AxSurfaceOptions<A>,
): ((...args: A) => CliReplyText | null) & AxSurfaceMeta<A> {
  const wrapped = (...args: A) => format(...args) as CliReplyText | null;
  return Object.assign(wrapped, { axDescription: description, axExamples: options.examples });
}

// Module-internal mint for this file's own constants (NL). Not exported: the
// axSurface wrapper above is the sole public brand outlet.
const mintCliReplyText = (text: string): CliReplyText => text as CliReplyText;

/**
 * Adapter-boundary escape hatch for reply text not yet produced by a
 * registered formatter. Migration-era only: the seam drift test records the
 * exact call-site count and it may only go down (target 0). Do not add call
 * sites to satisfy the compiler — move the string into a _format.ts formatter
 * instead.
 */
export const adoptCliReplyText = (text: string): CliReplyText => text as CliReplyText;

/** Branded newline glue for composing reply parts at write sites. */
export const NL: CliReplyText = mintCliReplyText("\n");

export function renderError(io: CliIo, err: CliError): void {
  const typed = err as CliError & {
    machinePayload?: unknown;
    /** Branded: typed error texts are agent-visible surfaces and must come from an axSurface producer. */
    typedText?: CliReplyText;
    outputMode?: "text" | "json";
  };
  if (typed.machinePayload !== undefined && typed.typedText) {
    io.stderr.write(
      typed.outputMode === "json"
        ? `${JSON.stringify(typed.machinePayload)}\n`
        : `${typed.typedText}\n`,
    );
    return;
  }

  const outputMode = typed.outputMode ?? "text";
  if (outputMode === "json") {
    const payload: Record<string, unknown> = {
      ok: false,
      error: {
        code: err.code,
        message: err.message,
        fault_domain: err.fault_domain ?? null,
        layer: err.layer ?? null,
        retryable: err.retryable ?? null,
        effect: err.effect ?? null,
        correlation_id: err.correlationId ?? null,
      },
    };
    if (err.effect_state) {
      payload.effect_state = err.effect_state;
    }
    const proxy = proxyDiagnosticsPayload(err);
    if (proxy) {
      (payload.error as Record<string, unknown>).proxy = proxy;
    }
    if (err.details) {
      payload.details = err.details;
    }
    if (err.suggestedNextAction) {
      (payload.error as Record<string, unknown>).next_action = err.suggestedNextAction;
    }
    io.stderr.write(`${JSON.stringify(payload)}\n`);
    return;
  }

  io.stderr.write(formatErrorEnvelope(err));
}

/**
 * The CLI error envelope: the labelled Error:/Code:/... block every command
 * failure prints to stderr. STATIC layout = the label set and their order;
 * DYNAMIC segments = each label's value from the specific CliError. Only the
 * lines whose fields are present render; textDetailMode
 * "omit_restated_lines" additionally drops the restating labels
 * (Effect/Draft saved/Next action) that the command already printed.
 */
export const formatErrorEnvelope = axSurface(
  "Labelled stderr error envelope (Error/Code/Retryable/… block) rendered for every text-mode command failure.",
  (err: CliError): string => {
    // Producer-declared: omit labelled lines that only restate what the command
    // already printed above. Classification lines are never omitted.
    const omitRestated = err.textDetailMode === "omit_restated_lines";
    const lines: string[] = [];
    lines.push(`Error: ${err.message}`);
    lines.push(`Code: ${err.code}`);
    if (err.fault_domain && err.fault_domain !== err.layer) {
      lines.push(`Fault domain: ${err.fault_domain}`);
    }
    if (err.layer) {
      lines.push(`Layer: ${err.layer}`);
    }
    if (err.retryable !== undefined) {
      lines.push(`Retryable: ${err.retryable === null ? "unknown" : err.retryable ? "yes" : "no"}`);
    }
    if (err.effect !== undefined && !omitRestated) {
      lines.push(`Effect: ${err.effect}`);
    }
    if (err.correlationId) {
      lines.push(`Correlation: ${err.correlationId}`);
    }
    if (err.proxyFailureClass) {
      lines.push(`Proxy failure class: ${err.proxyFailureClass}`);
    }
    if (err.proxyCauseCode) {
      lines.push(`Proxy cause code: ${err.proxyCauseCode}`);
    }
    if (err.proxyRouteFamily) {
      lines.push(`Proxy route family: ${err.proxyRouteFamily}`);
    }
    if (err.proxyUpstreamLayer) {
      lines.push(`Proxy upstream layer: ${err.proxyUpstreamLayer}`);
    }
    if (err.proxyUpstreamStatus !== undefined) {
      lines.push(`Proxy upstream status: ${err.proxyUpstreamStatus}`);
    }
    if (err.proxyResponseStarted !== undefined) {
      lines.push(`Proxy response started: ${err.proxyResponseStarted === null ? "unknown" : err.proxyResponseStarted ? "yes" : "no"}`);
    }
    if (err.proxyResponseComplete !== undefined) {
      lines.push(`Proxy response complete: ${err.proxyResponseComplete === null ? "unknown" : err.proxyResponseComplete ? "yes" : "no"}`);
    }
    if (err.draftSaved !== undefined && !omitRestated) {
      lines.push(`Draft saved: ${err.draftSaved ? "yes" : "no"}`);
    }
    if (err.effect_state) {
      lines.push(`Effect state: ${JSON.stringify(err.effect_state)}`);
    }
    if (err.suggestedNextAction && !omitRestated) {
      lines.push(`Next action: ${err.suggestedNextAction}`);
    }
    return lines.map((line) => `${line}\n`).join("");
  },
  {
    examples: [
      {
        title: "held-draft failure shape (SEND_HELD_AS_DRAFT)",
        args: [
          {
            message: "Message held as draft; no target delivery occurred.",
            code: "SEND_HELD_AS_DRAFT",
            retryable: false,
            draftSaved: true,
            effect: "draft_saved",
            textDetailMode: "omit_restated_lines",
          } as CliError,
        ],
      },
      {
        title: "server failure with next action",
        args: [
          {
            message: "HTTP 502 from server",
            code: "SERVER_5XX",
            layer: "server",
            retryable: true,
            suggestedNextAction: "Retry after checking server status.",
          } as CliError,
        ],
      },
    ],
  },
);

function proxyDiagnosticsPayload(err: CliError): Record<string, unknown> | null {
  if (
    !err.proxyFailureClass &&
    !err.proxyCauseCode &&
    !err.proxyRouteFamily &&
    !err.proxyUpstreamLayer &&
    err.proxyUpstreamStatus === undefined &&
    err.proxyResponseStarted === undefined &&
    err.proxyResponseComplete === undefined
  ) {
    return null;
  }
  return {
    correlation_id: err.correlationId ?? null,
    failure_class: err.proxyFailureClass ?? null,
    cause_code: err.proxyCauseCode ?? null,
    route_family: err.proxyRouteFamily ?? null,
    upstream_layer: err.proxyUpstreamLayer ?? null,
    upstream_status: err.proxyUpstreamStatus ?? null,
    response_started: err.proxyResponseStarted ?? null,
    response_complete: err.proxyResponseComplete ?? null,
  };
}

export function writeText(io: CliIo, ...parts: readonly CliReplyText[]): void {
  io.stdout.write(parts.join(""));
}

/**
 * Branded stderr twin of writeText for diagnostic reply text (degradation
 * signals, handoff prompts). Same seam rules: parts must come from registered
 * formatters; the print-seam gates pin every other stderr path.
 */
export function writeDiagnostic(io: CliIo, ...parts: readonly CliReplyText[]): void {
  io.stderr.write(parts.join(""));
}

export function writeJson(io: CliIo, payload: unknown): void {
  io.stdout.write(`${JSON.stringify(payload)}\n`);
}
