/**
 * Closed set of migration errors that can reach an owner-facing API/UI.
 *
 * The Server imports this type at every response boundary and the Web imports
 * the same type for exhaustive copy coverage. Adding a new user-visible code
 * therefore cannot compile until the UI supplies an actionable presentation.
 */
export const AGENT_MIGRATION_TERMINAL_FAILURE_CODES = [
  "MIGRATION_TRANSPORT_LOST",
  "MIGRATION_OBJECT_STORE_BUNDLE_TOO_LARGE",
  "MIGRATION_OBJECT_STORE_MANIFEST_TOO_LARGE",
  "MIGRATION_OBJECT_STORE_INSUFFICIENT_DISK",
  "MIGRATION_OBJECT_STORE_ENTRY_COUNT_LIMIT_EXCEEDED",
  "MIGRATION_WORKSPACE_ALREADY_EXISTS",
  "MIGRATION_WORKSPACE_COMPLETE_OLD_COPY",
  "MIGRATION_CHUNK_DIGEST_MISMATCH",
  "MIGRATION_WHOLE_BUNDLE_DIGEST_MISMATCH",
  "MIGRATION_LEASE_EXPIRED",
  "MIGRATION_GENERATION_STALE",
  "MIGRATION_CONTROL_MANIFEST_INVALID",
  "MIGRATION_CONTROL_MANIFEST_TOO_LARGE",
] as const;

export type AgentMigrationTerminalFailureCode =
  (typeof AGENT_MIGRATION_TERMINAL_FAILURE_CODES)[number];

export const AGENT_MIGRATION_USER_ERROR_CODES = [
  "agent_migration_ui_disabled",
  "not_supported",
  "AGENT_NOT_FOUND",
  "TARGET_COMPUTER_REQUIRED",
  "AGENT_HAS_NO_SOURCE_MACHINE",
  "TARGET_COMPUTER_NOT_IN_SERVER",
  "TARGET_COMPUTER_MATCHES_SOURCE",
  "COMPUTER_CAPABILITY_INSUFFICIENT",
  "TARGET_COMPUTER_OFFLINE",
  "MIGRATION_ALREADY_IN_PROGRESS",
  "MIGRATION_PRO_PLAN_REQUIRED",
  "MIGRATION_TRANSPORT_NOT_PROVISIONED",
  "MIGRATION_TRANSPORT_PROVISION_FAILED",
  "MIGRATION_RESUMABLE_CAPABILITY_REQUIRED",
  ...AGENT_MIGRATION_TERMINAL_FAILURE_CODES,
  "MIGRATION_REF_INVALID",
  "MIGRATION_REVISION_INVALID",
  "MIGRATION_NOT_FOUND",
  "MIGRATION_REVISION_STALE",
  "MIGRATION_CONCURRENT_UPDATE",
  "MIGRATION_CANCEL_FAILED",
  "MIGRATION_START_FAILED",
  "MIGRATION_STATUS_FAILED",
] as const;

export type AgentMigrationUserErrorCode = (typeof AGENT_MIGRATION_USER_ERROR_CODES)[number];
