import { EXAMPLE_T, exampleMessage, exampleRestartDriver, exampleStdinDriver, exampleUnreadSummary } from "./axExampleFixtures.js";
import {
  formatUtcTimestamp,
  formatProducerFactLineageBracket,
  renderThirdPartyInertJson,
  asAxSurfaceText,
  type AgentConfig,
  type AgentMessage,
  type AxSurfaceText,
} from "@botiverse/raft-shared";
import {
  formatAgentInboxDelta,
  formatAgentReplyAffordanceSuffix,
  projectAgentInboxSnapshot,
  type AgentInboxTargetRow,
} from "./agentInboxProjection.js";
import { formatAttachmentSuffix, type AttachmentDownloadHintStyle } from "./attachmentFormatting.js";
import type { AgentProxyVisibleMessage } from "./agentCredentialProxy.js";
import { formatAgentMessageVisibleTarget } from "./agentVisibleDeliveryLedger.js";
import type { RuntimeDriver } from "./drivers/types.js";

const RESPONSE_TARGET_HINT =
  "Reply in the channel or create/reply in a thread as appropriate; use each message's `target` and `msg` fields to choose the exact target.";

// AxSurfaceText brand + mint live in @botiverse/raft-shared (next to Brand, per
// brandedIds doctrine) so drivers/types can name the type without a cycle.
export type { AxSurfaceText } from "@botiverse/raft-shared";

export interface AxSurfaceExample<A extends readonly unknown[]> {
  readonly title?: string;
  /** One invocation's arguments, typechecked against the formatter's own parameter tuple. */
  readonly args: A;
}

export interface AxSurfaceOptions<A extends readonly unknown[]> {
  /** REQUIRED and non-empty (@xxchan ruling): a surface without an example does not compile. */
  readonly examples: readonly [AxSurfaceExample<A>, ...AxSurfaceExample<A>[]];
}

export type AxSurfaceMeta<A extends readonly unknown[]> = {
  readonly axDescription: string;
  readonly axExamples: readonly AxSurfaceExample<A>[];
};

/**
 * Define a registered agent-visible runtime-input surface. Sole public brand
 * outlet on the daemon side (besides the pinned adoptAxSurfaceText escape):
 * the ax-surfaces manifest is generated by scanning `axSurface(`/
 * `axSurfaceLiteral(` call sites, so defining a surface and registering it are
 * the same act. Description AND at least one typed example live in the same
 * expression; the AX HTML renders fn(...example.args) via the attached
 * axExamples. Descriptions must be string literals.
 */
export function axSurface<A extends readonly unknown[]>(
  description: string,
  format: (...args: A) => string,
  options: AxSurfaceOptions<A>,
): ((...args: A) => AxSurfaceText) & AxSurfaceMeta<A>;
export function axSurface<A extends readonly unknown[]>(
  description: string,
  format: (...args: A) => string | null,
  options: AxSurfaceOptions<A>,
): ((...args: A) => AxSurfaceText | null) & AxSurfaceMeta<A>;
export function axSurface<A extends readonly unknown[]>(
  description: string,
  format: (...args: A) => string | null,
  options: AxSurfaceOptions<A>,
): ((...args: A) => AxSurfaceText | null) & AxSurfaceMeta<A> {
  const wrapped = (...args: A) => format(...args) as AxSurfaceText | null;
  return Object.assign(wrapped, { axDescription: description, axExamples: options.examples });
}

/** Literal (argument-free) registered surface. */
export function axSurfaceLiteral(description: string, text: string): AxSurfaceText {
  void description;
  return text as AxSurfaceText;
}

export function composeAxSurfaces(...parts: readonly AxSurfaceText[]): AxSurfaceText {
  return asAxSurfaceText(parts.join(""));
}

/**
 * Adapter-boundary escape hatch for runtime input that is not produced by a
 * registered formatter in this turn: a resume prompt restored from persisted
 * state, and a standing prompt built by the driver (itself the registered
 * standing_prompt surface, typed at the RuntimeDriver seam as string).
 * Do not add call sites to satisfy the compiler — register a formatter
 * instead. The registry drift test pins the exact call-site count in
 * agentProcessManager.ts.
 */
export const adoptAxSurfaceText = (text: string): AxSurfaceText => asAxSurfaceText(text);

type IncomingMessageFormatOptions = {
  attachmentHint?: AttachmentDownloadHintStyle;
};

function getMessageShortId(messageId: string): string {
  return messageId.startsWith("thread-") ? messageId.slice(7) : messageId.slice(0, 8);
}

function formatSenderHandle(message: { sender_name: string; sender_description?: string | null }): string {
  return message.sender_description
    ? `@${message.sender_name} — ${message.sender_description}`
    : `@${message.sender_name}`;
}

function formatVisibleActorType(type: AgentMessage["sender_type"]): string {
  return ` type=${type}`;
}

function formatThreadContextMessage(
  message: NonNullable<AgentMessage["thread_join_context"]>["parent_message"],
): string {
  const msgId = message.message_id ? getMessageShortId(message.message_id) : "-";
  const time = message.timestamp ? formatUtcTimestamp(message.timestamp) : "-";
  const senderType = formatVisibleActorType(message.sender_type);
  const seq = typeof message.seq === "number" ? ` seq=${message.seq}` : "";
  return `- [msg=${msgId}${seq} time=${time}${senderType}] ${formatSenderHandle(message)}: ${message.content}`;
}

function formatIncomingMessage(message: AgentMessage, options: IncomingMessageFormatOptions): string {
  const threadJoinPrefix = message.thread_join_context
    ? [
        "[Raft thread context: you were mentioned in a thread without model-visible context.]",
        `parent: ${message.thread_join_context.parent_target}`,
        `thread: ${message.thread_join_context.thread_target}`,
        `suggested next step: raft message read --target "${message.thread_join_context.suggested_read_history_target}"`,
        "",
        "Parent message:",
        formatThreadContextMessage(message.thread_join_context.parent_message),
        "",
        `Recent thread context${message.thread_join_context.history_truncated ? " (truncated)" : ""}:`,
        message.thread_join_context.recent_messages.length > 0
          ? message.thread_join_context.recent_messages.map(formatThreadContextMessage).join("\n")
          : "- (no earlier thread replies)",
        "",
      ].join("\n")
    : "";
  const threadFollowReactivationPrefix = message.thread_follow_reactivation
    ? [
        `[Raft thread follow restored: this @mention re-subscribed you to ordinary replies in ${message.thread_follow_reactivation.thread_target}.]`,
        `To stop those replies again: raft thread unfollow --target ${JSON.stringify(message.thread_follow_reactivation.thread_target)}`,
        "",
      ].join("\n")
    : "";
  const target = formatAgentMessageVisibleTarget(message);
  const msgId = message.message_id ? getMessageShortId(message.message_id) : "-";
  const time = message.timestamp ? formatUtcTimestamp(message.timestamp) : "-";
  const senderType = formatVisibleActorType(message.sender_type);
  const attachSuffix = formatAttachmentSuffix(message.attachments, options.attachmentHint);
  const taskSuffix = message.task_status
    ? ` [task #${message.task_number} status=${message.task_status}${message.task_assignee_id ? ` assignee=${message.task_assignee_type ?? null}:${message.task_assignee_id}` : ""}]`
    : "";
  const lineageSuffix = formatProducerFactLineageBracket(message.producerFactId);
  const body = `[target=${target} msg=${msgId} time=${time}${senderType}] ${formatSenderHandle(message)}: ${message.content}${message.third_party_event ? `\npayload:\n${renderThirdPartyInertJson(message.third_party_event.payload)}` : ""}${attachSuffix}${taskSuffix}${lineageSuffix}${formatAgentReplyAffordanceSuffix(message)}`;
  const prefixes = [threadJoinPrefix, threadFollowReactivationPrefix].filter(Boolean);
  return prefixes.length > 0 ? `${prefixes.join("\n")}\n${body}` : body;
}

function incomingMessageFormatOptionsForDriver(driver: RuntimeDriver): IncomingMessageFormatOptions {
  switch (driver.communication.chat) {
    case "slock_cli":
      return { attachmentHint: "slock_cli" };
  }
}

export const formatSystemNoticeRuntimeInput = axSurface(
  "System notice envelope around a single system message.",
  (message: AgentMessage, driver: RuntimeDriver): string => {
  return (`System notice received:\n\n${formatIncomingMessage(message, incomingMessageFormatOptionsForDriver(driver))}\n\nRespond as appropriate. Complete all your work before stopping.\n${RESPONSE_TARGET_HINT}`);
},
  {
    examples: [{ args: [{ ...exampleMessage, sender_name: "System", sender_type: "system", content: "\ud83d\udccc Assigned @alice-agent to task #42 \"do the thing\"" }, exampleStdinDriver] }],
  },
);

export const formatConcreteMessagesRuntimeInput = axSurface(
  "New message(s) delivered into a turn: header, sender, content, and all suffix variants (attachments, task projection, third-party payload, thread-join context, follow reactivation, reply affordance).",
  (
  messages: readonly AgentMessage[],
  driver: RuntimeDriver,
  pendingInboxNotice?: string,
): string => {
  const header = messages.length === 1 ? "New message received:" : "New messages received:";
  const concreteMessages = messages
    .map((message) => formatIncomingMessage(message, incomingMessageFormatOptionsForDriver(driver)))
    .join("\n");
  return (`${header}\n\n${concreteMessages}${pendingInboxNotice ? `\n\n${pendingInboxNotice}` : ""}\n\nRespond as appropriate. Complete all your work before stopping.\n${RESPONSE_TARGET_HINT}`);
},
  {
    // Delivery examples cover all four target shapes (@xxchan 8/31):
    // channel, channel thread, dm, dm thread.
    examples: [{ title: "plain channel message", args: [[exampleMessage], exampleStdinDriver] }, { title: "channel thread (thread-join context prefix)", args: [[{ ...exampleMessage, channel_type: "thread", channel_name: "thread-aaaabbbb-0000-0000-0000-000000000000", parent_channel_name: "general", parent_channel_type: "channel", content: "@alice-agent what do you think?", mentioned: true, thread_join_context: { reason: "mentioned", parent_target: "#general", thread_target: "#general:aaaabbbb", suggested_read_history_target: "#general:aaaabbbb", parent_message: { message_id: "aaaabbbb-0000-0000-0000-000000000000", sender_name: "richard", sender_type: "human", content: "let's discuss the rollout plan", timestamp: EXAMPLE_T, seq: 90 }, recent_messages: [], history_truncated: true } }], exampleStdinDriver] }, { title: "dm", args: [[{ ...exampleMessage, channel_type: "dm", channel_name: "richard", content: "hey, can you help?" }], exampleStdinDriver] }, { title: "dm thread reply", args: [[{ ...exampleMessage, channel_type: "thread", channel_name: "thread-00000000-1111-2222-3333-444444444444", parent_channel_name: "richard", parent_channel_type: "dm", content: "following up in our DM thread" }], exampleStdinDriver] }, { title: "attachments + task bracket + non-member mention", args: [[{ ...exampleMessage, mentioned: true, non_member_mention: true, attachments: [{ id: "aaaa1111-0000-0000-0000-000000000000", filename: "spec.md", mimeType: "text/markdown", sizeBytes: 12345 }], task_status: "in_progress", task_number: 42, task_assignee_type: "agent", task_assignee_id: "agent-1" }], exampleStdinDriver] }],
  },
);

export const formatInboxUpdateRuntimeInput = axSurface(
  "Content-free [Raft inbox notice: ...] batched into a busy turn or delivered as a wake.",
  (
  messages: readonly AgentMessage[],
  _driver: RuntimeDriver,
  totalPendingMessages: number = messages.length,
): string => {
  const rows = projectAgentInboxSnapshot(messages);
  return ([
    "[Raft inbox notice:",
    formatAgentInboxDelta(rows, { totalPendingMessages }),
    "]",
    "These messages have not been read. Choose when to read them with `raft message check` or `raft message read --target <target>`; deferring them does not establish that there is no work.",
  ].join("\n"));
},
  {
    // Rows cover all four target shapes (@xxchan 8/31): channel, channel
    // thread, dm, dm thread.
    examples: [{ args: [[{ ...exampleMessage, mentioned: true }, { ...exampleMessage, message_id: "55555555-6666-7777-8888-999999999999", seq: 101, channel_type: "dm", channel_name: "richard" }, { ...exampleMessage, message_id: "aaaabbbb-0000-0000-0000-000000000000", seq: 102, channel_type: "thread", channel_name: "thread-aaaabbbb", parent_channel_name: "general", parent_channel_type: "channel" }, { ...exampleMessage, message_id: "ccccdddd-0000-0000-0000-000000000000", seq: 103, channel_type: "thread", channel_name: "thread-55555555", parent_channel_name: "richard", parent_channel_type: "dm" }], exampleStdinDriver, 7] }],
  },
);

export function inboxProjectionTraceAttrs(
  rows: readonly AgentInboxTargetRow[],
  pendingMessageCount: number,
): Record<string, unknown> {
  let maxPendingCount = 0;
  let mentionTargetCount = 0;
  let threadTargetCount = 0;
  let dmTargetCount = 0;
  let taskTargetCount = 0;
  let attentionHintTargetCount = 0;
  for (const row of rows) {
    maxPendingCount = Math.max(maxPendingCount, row.pendingCount);
    if (row.flags.includes("mention")) mentionTargetCount += 1;
    if (row.flags.includes("thread")) threadTargetCount += 1;
    if (row.flags.includes("dm")) dmTargetCount += 1;
    if (row.flags.includes("task")) taskTargetCount += 1;
    if (row.attentionHint) attentionHintTargetCount += 1;
  }
  return {
    target_count: rows.length,
    changed_target_count: rows.length,
    inbox_target_count: rows.length,
    pending_message_count: pendingMessageCount,
    max_pending_per_target: maxPendingCount,
    mention_target_count: mentionTargetCount,
    thread_target_count: threadTargetCount,
    dm_target_count: dmTargetCount,
    task_target_count: taskTargetCount,
    attention_hint_target_count: attentionHintTargetCount,
  };
}

export function projectThreadJoinContextsForRuntimeInput(
  messages: readonly AgentMessage[],
  getVisibleBoundary: (target: string) => number | undefined,
  renderContext = true,
): { messages: AgentMessage[]; renderedContextMessages: AgentMessage[] } {
  const selectedIndexByTarget = new Map<string, number>();
  for (let index = 0; renderContext && index < messages.length; index += 1) {
    const context = messages[index].thread_join_context;
    if (context && getVisibleBoundary(context.thread_target) === undefined) {
      selectedIndexByTarget.set(context.thread_target, index);
    }
  }

  const renderedContextMessages: AgentMessage[] = [];
  const projectedMessages = messages.map((message, index) => {
    const context = message.thread_join_context;
    if (!context) return message;
    if (selectedIndexByTarget.get(context.thread_target) === index) {
      renderedContextMessages.push(message);
      return message;
    }
    const { thread_join_context: _omitted, ...projected } = message;
    return projected;
  });
  return { messages: projectedMessages, renderedContextMessages };
}

// --- Wake/startup surfaces (moved verbatim from agentProcessManager.ts) ---
// These are agent-visible text faces. Every function here must stay pure and
// defined via axSurface() so the generated ax-surfaces.manifest.json stays complete.

// Claude Code 2.1.114 treats "follow your system prompt" style user turns as
// prompt-injection bait even when the prompt is supplied via --system-prompt-file.
// A neutral starter lets the native standing prompt drive startup/migration.
export const NATIVE_STANDING_PROMPT_STARTUP_INPUT: AxSurfaceText = axSurfaceLiteral(
  "Neutral starter turn for native-standing-prompt drivers.",
  "Start."
);

function formatUnreadChannelLines(unreadSummary: Record<string, number>): string {
  let lines = "";
  for (const [ch, count] of Object.entries(unreadSummary)) {
    lines += `\n- ${ch}: ${count} unread`;
  }
  return lines;
}

export const formatOtherUnreadChannelsSuffix = axSurface(
  "Wake-delivery suffix listing other channels with unread counts.",
  (unreadSummary: Record<string, number> | undefined): string => {
  if (!unreadSummary || Object.keys(unreadSummary).length === 0) return ("");
  return (`\n\nYou also have unread messages in other channels:${formatUnreadChannelLines(unreadSummary)}\n\nUse the inbox/read commands at a natural breakpoint if you choose to inspect those targets.`);
},
  {
    examples: [{ args: [exampleUnreadSummary] }],
  },
);

export const formatBoundedStartupUnreadSuffix = axSurface(
  "Resume catch-up suffix warning that the startup batch is bounded.",
  (unreadSummary: Record<string, number> | undefined): string => {
  if (!unreadSummary || Object.keys(unreadSummary).length === 0) return ("");
  return (`\n\nSome unread channels may not be included in this bounded startup batch:${formatUnreadChannelLines(unreadSummary)}\n\nUse the inbox/read commands at a natural breakpoint if you choose to inspect those targets.`);
},
  {
    examples: [{ args: [exampleUnreadSummary] }],
  },
);

export const formatResumeUnreadSummaryPrompt = axSurface(
  "Constrained offline catch-up mode prompt (read listed channels once; act only if directly addressed).",
  (
  unreadSummary: Record<string, number>,
  _driver: RuntimeDriver,
): string => {
  return (`You have unread messages from while you were offline:${formatUnreadChannelLines(unreadSummary)}\n\nUse \`raft message read\` to catch up on the channels listed above, then stop. Read each listed channel at most once unless a read fails. Do NOT call \`raft message check\` in this mode. If the history reveals a direct request, assignment, @mention, review request, or task clearly addressed to you, switch into active handling instead of stopping: reply using \`raft message send --target <exact target>\` and claim the relevant task with \`raft task claim\` before starting work. Otherwise, do NOT send any message in this mode.`);
},
  {
    examples: [{ args: [exampleUnreadSummary, exampleStdinDriver] }],
  },
);

export const formatResumeEmptyPrompt = axSurface(
  "Nothing-pending resume prompt.",
  (_driver: RuntimeDriver): string => {
  return "No new messages while you were away. Nothing to do — just stop.";
},
  {
    examples: [{ title: "stdin-notification driver", args: [exampleStdinDriver] }, { title: "restart driver", args: [exampleRestartDriver] }],
  },
);

// --- Runtime Profile control surfaces (moved verbatim from agentProcessManager.ts) ---

export type RuntimeProfileControlKind = "migration" | "daemon_release_notice";

export const RUNTIME_PROFILE_MIGRATION_MESSAGE_PREFIX = "runtime-profile-migration-";
export const RUNTIME_PROFILE_DAEMON_NOTICE_MESSAGE_PREFIX = "runtime-profile-daemon-release-";

export function runtimeProfileNotificationFromMessage(message: AgentMessage): { kind: RuntimeProfileControlKind; key: string } | null {
  if (message.message_id?.startsWith(RUNTIME_PROFILE_MIGRATION_MESSAGE_PREFIX)) {
    return { kind: "migration", key: message.message_id.slice(RUNTIME_PROFILE_MIGRATION_MESSAGE_PREFIX.length) };
  }
  if (message.message_id?.startsWith(RUNTIME_PROFILE_DAEMON_NOTICE_MESSAGE_PREFIX)) {
    return { kind: "daemon_release_notice", key: message.message_id.slice(RUNTIME_PROFILE_DAEMON_NOTICE_MESSAGE_PREFIX.length) };
  }
  return null;
}

/**
 * Wrap a batch of inbox-pipeline runtime-profile notifications into a
 * single stdin prompt. This is the **live-delivery** path: the agent
 * process already exists and is reading stdin, and the server has just
 * pushed one or more messages whose `message_id` is a runtime-profile
 * prefix (`runtime-profile-migration-...` or
 * `runtime-profile-daemon-release-...`).
 *
 * Two call sites:
 * - spawn-time when the wakeMessage *itself* is a runtime-profile
 *   notification (no `runtimeProfileControl` config — the control was
 *   already pushed via the inbox before the agent woke);
 * - live delivery (`AgentProcessManager.deliverInbox`-equivalent) when
 *   a stdin batch contains one or more runtime-profile notifications.
 *
 * Returns `null` if the batch contains zero notifications or any
 * non-notification (the caller falls back to the regular new-message
 * prompt).
 *
 * Sibling: `formatRuntimeProfileControlStartupInput` handles the
 * spawn-time `AgentConfig.runtimeProfileControl` field path — that's
 * a single, non-message-shaped control attached to the spawn config
 * before the agent process exists. Both produce stdin prompts but the
 * upstream source differs (inbox-pipeline message batch vs spawn-config
 * field).
 */
export const formatRuntimeProfileControlPrompt = axSurface(
  "Runtime Profile notice wrapping a batch of inbox-pipeline runtime-profile notifications (live-delivery path).",
  (messages: AgentMessage[]): string | null => {
  const controls = messages.map((message) => ({
    message,
    notification: runtimeProfileNotificationFromMessage(message),
  }));
  if (controls.length === 0 || controls.some(({ notification }) => !notification || notification.kind !== "daemon_release_notice")) {
    return null;
  }

  const body = controls.map(({ message }) => message.content).join("\n\n---\n\n");

  return ([
    "Runtime Profile notice.",
    "",
    "Read the daemon release notice below before continuing. No chat reply or runtime control action is required — resume normal inbox processing afterward.",
    "",
    body,
  ].join("\n"));
},
  {
    examples: [{ args: [[{ ...exampleMessage, sender_name: "System", sender_type: "system", content: "Daemon v1.0.24 released: <release notice body>", message_id: "runtime-profile-daemon-release-example-key" }]] }],
  },
);

/**
 * Wrap the spawn-time `AgentConfig.runtimeProfileControl` field into
 * the agent's startup stdin input. This is the **spawn-time** path:
 * the agent process is just being created and there is no inbox /
 * stdin to receive a message-shaped notification yet, so the server
 * attached the control directly to the spawn config (see the JSDoc on
 * `AgentConfig.runtimeProfileControl` in `@botiverse/raft-shared`).
 *
 * One call site: in `startAgent`, when `runtimeProfileControl` is set
 * AND no `wakeMessage` exists. (When a `wakeMessage` exists and is
 * itself a runtime-profile notification, that takes precedence and
 * goes through `formatRuntimeProfileControlPrompt` instead.)
 *
 * Sibling: `formatRuntimeProfileControlPrompt` handles the inbox /
 * live-delivery message-batch path. Both produce stdin prompts but
 * the upstream source differs — config field vs message pipeline —
 * and they're invoked in mutually exclusive lifecycle moments.
 *
 * The two functions could be unified (rewrite spawn-time delivery to
 * inject a synthetic message into the inbox post-spawn), but the cost
 * is a new spawn-then-inject protocol time-window and is out of scope
 * here. Tracked separately if we ever do it.
 */
export const formatRuntimeProfileControlStartupInput = axSurface(
  "Runtime Profile daemon release notice attached to spawn config (spawn-time path).",
  (
  control: NonNullable<AgentConfig["runtimeProfileControl"]>,
  driver: RuntimeDriver,
): string => {
  void driver;
  return ([
    "Read the Runtime Profile daemon release notice from your system prompt before normal work.",
    "No chat reply or runtime control action is required for this notice. Stop after reading it; queued inbox messages will be delivered separately.",
    "",
    control.message,
  ].join("\n"));
},
  {
    examples: [{ args: [{ kind: "daemon_release_notice", message: "Daemon v1.0.24 released: <release notice body>" } as never, exampleStdinDriver] }],
  },
);

export function groupThreadJoinContextReceiptMessages(
  messages: readonly AgentMessage[],
): Map<string, AgentProxyVisibleMessage[]> {
  const messagesByTarget = new Map<string, AgentProxyVisibleMessage[]>();
  const add = (target: string, message: AgentProxyVisibleMessage) => {
    const targetMessages = messagesByTarget.get(target) ?? [];
    targetMessages.push(message);
    messagesByTarget.set(target, targetMessages);
  };

  for (const message of messages) {
    const context = message.thread_join_context;
    if (!context) continue;
    add(context.parent_target, context.parent_message);
    for (const recentMessage of context.recent_messages) {
      add(context.thread_target, recentMessage);
    }
  }
  return messagesByTarget;
}
