import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { buildAgentApiRouteManifest } from "../src/agentApiContract.js";

const outFile = resolve(import.meta.dirname, "../src/generated/agentApiRoutes.ts");
const manifest = buildAgentApiRouteManifest();

writeFileSync(
  outFile,
  [
    "// Generated by packages/shared/scripts/generate-agent-api-routes.ts. Do not edit by hand.",
    "",
    `export const AGENT_API_ROUTE_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;`,
    "",
  ].join("\n"),
);
