// agent-facing env-var auth bootstrap.
//
// Two distinct entry shapes are supported:
//
// A. **External agent (preferred, post-RFC v0.8)**
//    `RAFT_PROFILE=<slug>` resolves a credential file at
//    `~/.slock/profiles/<slug>/credential.json` written by `raft agent login`
//    (device-code grant → `sk_agent_*` mint). The profile file carries
//    serverUrl, agentId, optional serverId, and the apiKey, so the user
//    doesn't have to re-export those by hand. The CLI flag `--profile <slug>`
//    sets this env var for convenience.
//    WIP(self-hosted-runner-layer1): this is only the credential/profile
//    entry layer. It does not implement runner lifecycle, process ownership,
//    heartbeat/status, stop/revoke orchestration, or runtime integration.
//
// B. **Daemon-injected runner**
//    The daemon spawns the agent process and injects
//    SLOCK_AGENT_PROXY_URL + SLOCK_AGENT_PROXY_TOKEN_FILE. The daemon keeps
//    the canonical sk_agent_* in memory; the short-lived CLI reads only a
//    daemon-owned local proxy token. SLOCK_AGENT_PROXY_TOKEN remains accepted
//    for tests and older builds.
//
//    Legacy SLOCK_AGENT_TOKEN(_FILE) machine-token bootstraps are rejected:
//    the CLI no longer carries a `/internal/agent/:id/*` machine route path.
//
// Outside a managed runtime, mode (A) takes precedence: if RAFT_PROFILE is
// set, raw agent env vars are ignored and the override is logged to stderr.
// Inside a managed runtime, a profile selector is an identity conflict and
// fails closed. Managed launches must stay bound to the daemon-owned wrapper
// identity; an rc-file profile must never silently replace it.
//
// Required for mode (B): SLOCK_AGENT_ID, SLOCK_SERVER_URL.
// Optional: SLOCK_SERVER_ID — server resolves it from machine auth in v0;
// kept as forward-compat hook for milestone-2 agent-token mode.

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

export interface AgentContext {
  agentId: string;
  serverUrl: string;
  serverId: string | null;
  token: string;
  /**
   * Wire-behavior tag: which route surface this invocation hits and where its
   * bearer comes from. This is NOT an entry-shape tag (managed vs
   * external agent) — that distinction lives in `secretSource`.
   *
   *   - managed-runner      : daemon-local proxy; daemon holds sk_agent_*,
   *                           CLI carries a short-lived proxy token. Always
   *                           a daemon-spawned managed runtime.
   *   - self-hosted-runner  : CLI calls /internal/agent-api/* directly with
   *                           a real sk_agent_* loaded from a profile
   *                           credential file created by
   *                           `raft agent login`.
   * The literal values are pinned by Computer/Agent Runner contract §11.
   * `self-hosted-runner` is the target product model; in this PR it covers
   * layer 1 only: a profile credential generated by `raft agent login` and
   * used by the CLI to call `/internal/agent-api/*` directly. Lifecycle and
   * runtime integration are later layers of the self-hosted runner contract.
   * WIP(self-hosted-runner-layer1): do not treat this as a complete runner.
   */
  clientMode: "managed-runner" | "self-hosted-runner";
  /**
   * Where the local secret material was loaded from. Kept separate from
   * clientMode so proxy transport does not read like a new token principal.
   */
  secretSource:
    | "agent-proxy-token-file"
    | "agent-proxy-token-env"
    | "profile-credential-file";
  activeCapabilities: string[] | null;
  /**
   * For profile-credential mode: where on disk the credential file lives.
   * Useful for `whoami` / debugging without leaking the bearer.
   */
  profileSlug?: string;
  profileCredentialPath?: string;
}

interface ProfileCredentialFile {
  schemaVersion?: number;
  serverUrl: string;
  agentId: string;
  agentName?: string;
  serverId?: string | null;
  credentialId?: string;
  scopes?: string[];
  apiKey: string;
  createdAt?: string;
}

const RAW_AGENT_ENV_KEYS = [
  "SLOCK_AGENT_ID",
  "SLOCK_SERVER_URL",
  "SLOCK_SERVER_ID",
  "SLOCK_AGENT_PROXY_URL",
  "SLOCK_AGENT_PROXY_TOKEN",
  "SLOCK_AGENT_PROXY_TOKEN_FILE",
  "SLOCK_AGENT_TOKEN_FILE",
  "SLOCK_AGENT_TOKEN",
] as const;

export class AgentBootstrapError extends Error {
  constructor(public readonly code: string, message: string) {
    super(message);
    this.name = "AgentBootstrapError";
  }
}

/**
 * Effective profile-credential root, in precedence order:
 *
 *   1. `RAFT_PROFILE_DIR` — explicit override of the per-profile directory
 *      (the test/fixture/operator escape hatch; targets a single profile).
 *   2. `RAFT_HOME/profiles/<slug>` — the app-level user-data root under the
 *      current brand. Falls back to reading `SLOCK_HOME` NOT as a brand
 *      alias but as the §10 state-isolation invariant (Dayu
 *      #wg-raft-computer msg=15528a10): the daemon exports SLOCK_HOME for
 *      all user-visible state until its own rename lands, and ignoring it
 *      would leak profile state outside the isolation root.
 *   3. `$HOME/.slock/profiles/<slug>` — fallback for un-managed shells where
 *      none of the above is exported. The PHYSICAL root stays `~/.slock`
 *      (#proj-aiax 2026-06-12, Stone/Dozy: the state root is a runtime/data
 *      anchor decoupled from the brand — same precedent as the `daemons`
 *      DB table; only env NAMES carry the new brand).
 *
 * `login.ts` MUST resolve via the same function so a write at login time
 * lands at the same path a subsequent `--profile <slug>` read uses.
 */
export function resolveProfileDir(slug: string, env: NodeJS.ProcessEnv = process.env): string {
  if (env.RAFT_PROFILE_DIR && env.SLOCK_PROFILE_DIR && env.RAFT_PROFILE_DIR !== env.SLOCK_PROFILE_DIR) {
    throw new AgentBootstrapError(
      "PROFILE_ENV_CONFLICT",
      `RAFT_PROFILE_DIR and SLOCK_PROFILE_DIR disagree; unset one (RAFT_PROFILE_DIR is canonical).`,
    );
  }
  const profileDir = env.RAFT_PROFILE_DIR ?? env.SLOCK_PROFILE_DIR;
  if (profileDir) {
    return profileDir;
  }
  const homeRoot = env.RAFT_HOME ?? env.SLOCK_HOME;
  if (homeRoot) {
    return path.join(homeRoot, "profiles", slug);
  }
  const home = env.HOME ?? os.homedir();
  return path.join(home, ".slock", "profiles", slug);
}

function resolveProfileCredentialPath(slug: string, env: NodeJS.ProcessEnv): string {
  return path.join(resolveProfileDir(slug, env), "credential.json");
}

function readProfileCredential(slug: string, env: NodeJS.ProcessEnv): {
  filePath: string;
  data: ProfileCredentialFile;
} {
  const filePath = resolveProfileCredentialPath(slug, env);
  let raw: string;
  try {
    raw = fs.readFileSync(filePath, "utf-8");
  } catch (err) {
    throw new AgentBootstrapError(
      "PROFILE_FILE_UNREADABLE",
      `RAFT_PROFILE=${slug} resolved to ${filePath}, which could not be read: ${(err as Error).message}. Run \`raft agent login\` to mint a credential.`,
    );
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err) {
    throw new AgentBootstrapError(
      "PROFILE_FILE_INVALID",
      `${filePath} is not valid JSON: ${(err as Error).message}`,
    );
  }
  if (
    !parsed
    || typeof parsed !== "object"
    || typeof (parsed as ProfileCredentialFile).apiKey !== "string"
    || typeof (parsed as ProfileCredentialFile).agentId !== "string"
    || typeof (parsed as ProfileCredentialFile).serverUrl !== "string"
  ) {
    throw new AgentBootstrapError(
      "PROFILE_FILE_INVALID",
      `${filePath} is missing required fields (apiKey, agentId, serverUrl).`,
    );
  }
  return { filePath, data: parsed as ProfileCredentialFile };
}

function readTokenFromFile(filePath: string, envName: string): string {
  let raw: string;
  try {
    raw = fs.readFileSync(filePath, "utf-8");
  } catch (err) {
    throw new AgentBootstrapError(
      "TOKEN_FILE_UNREADABLE",
      `${envName}=${filePath} could not be read: ${(err as Error).message}`,
    );
  }
  const token = raw.trim();
  if (!token) {
    throw new AgentBootstrapError(
      "TOKEN_FILE_EMPTY",
      `${envName}=${filePath} is empty`,
    );
  }
  return token;
}

export function loadAgentContext(env: NodeJS.ProcessEnv = process.env): AgentContext {
  const activeCapabilities = env.SLOCK_AGENT_ACTIVE_CAPABILITIES
    ? env.SLOCK_AGENT_ACTIVE_CAPABILITIES.split(",").map((cap) => cap.trim()).filter(Boolean)
    : null;

  // (A) External agent: profile credential file is the single source of
  // truth for serverUrl/agentId/apiKey. Profile wins over any raw agent env
  // vars that happen to be set (typical case: user runs `raft --profile X`
  // inside a daemon-spawned shell that already exports SLOCK_AGENT_*). We log
  // the override to stderr so the identity switch is visible — silent
  // shadowing here would make "why am I posting as the wrong agent?" a
  // nightmare to debug.
  // Alias window (Stone's env ruling, #proj-aiax 2026-06-12): RAFT_PROFILE
  // is the canonical name; SLOCK_PROFILE stays readable as a deprecation
  // alias. Both set to DIFFERENT values is an identity conflict and fails
  // loudly — silently picking one would let an agent post as the wrong
  // identity.
  if (env.RAFT_PROFILE && env.SLOCK_PROFILE && env.RAFT_PROFILE !== env.SLOCK_PROFILE) {
    throw new AgentBootstrapError(
      "PROFILE_ENV_CONFLICT",
      `RAFT_PROFILE=${env.RAFT_PROFILE} and SLOCK_PROFILE=${env.SLOCK_PROFILE} disagree; unset one (RAFT_PROFILE is canonical, SLOCK_PROFILE is a deprecation alias).`,
    );
  }
  const profileSlug = env.RAFT_PROFILE ?? env.SLOCK_PROFILE;
  if (profileSlug) {
    const managedLaunch = Boolean(
      env.SLOCK_CLI_TRANSPORT_DIR
      || (env.SLOCK_AGENT_LAUNCH_DIR && env.SLOCK_AGENT_ID && env.SLOCK_SERVER_URL),
    );
    if (managedLaunch) {
      throw new AgentBootstrapError(
        "PROFILE_MANAGED_CONTEXT_CONFLICT",
        `RAFT_PROFILE=${profileSlug} cannot select a different identity inside a managed Raft runtime. Remove RAFT_PROFILE/SLOCK_PROFILE from shell startup files and restart the runtime; the managed wrapper identity was not replaced.`,
      );
    }
    const shadowed = RAW_AGENT_ENV_KEYS.filter((k) => env[k]);
    if (shadowed.length > 0) {
      process.stderr.write(
        `raft: RAFT_PROFILE=${profileSlug} active; ignoring ${shadowed.join(", ")} from env.\n`,
      );
    }
    const { filePath, data } = readProfileCredential(profileSlug, env);
    return {
      agentId: data.agentId,
      serverUrl: data.serverUrl,
      serverId: data.serverId ?? null,
      token: data.apiKey,
      clientMode: "self-hosted-runner",
      secretSource: "profile-credential-file",
      activeCapabilities,
      profileSlug,
      profileCredentialPath: filePath,
    };
  }

  // (B) Daemon-injected runner bootstrap.
  const agentId = env.SLOCK_AGENT_ID;
  const serverUrl = env.SLOCK_SERVER_URL;
  const serverId = env.SLOCK_SERVER_ID ?? null;

  if (!agentId) throw new AgentBootstrapError("MISSING_AGENT_ID", "SLOCK_AGENT_ID is required");
  if (!serverUrl) throw new AgentBootstrapError("MISSING_SERVER_URL", "SLOCK_SERVER_URL is required");

  const agentProxyUrl = env.SLOCK_AGENT_PROXY_URL;
  const agentProxyToken = env.SLOCK_AGENT_PROXY_TOKEN;
  const agentProxyTokenFile = env.SLOCK_AGENT_PROXY_TOKEN_FILE;
  if (agentProxyUrl || agentProxyToken || agentProxyTokenFile) {
    if (!agentProxyUrl) {
      throw new AgentBootstrapError("MISSING_AGENT_PROXY_URL", "SLOCK_AGENT_PROXY_URL is required when agent proxy auth is set");
    }
    if (agentProxyToken && agentProxyTokenFile) {
      throw new AgentBootstrapError(
        "MULTIPLE_AGENT_PROXY_TOKENS",
        "Set only one of SLOCK_AGENT_PROXY_TOKEN or SLOCK_AGENT_PROXY_TOKEN_FILE",
      );
    }
    const token = agentProxyToken ?? (agentProxyTokenFile ? readTokenFromFile(agentProxyTokenFile, "SLOCK_AGENT_PROXY_TOKEN_FILE") : null);
    if (!token) {
      throw new AgentBootstrapError(
        "MISSING_AGENT_PROXY_TOKEN",
        "SLOCK_AGENT_PROXY_TOKEN_FILE or SLOCK_AGENT_PROXY_TOKEN is required when SLOCK_AGENT_PROXY_URL is set",
      );
    }
    return {
      agentId,
      serverUrl: agentProxyUrl,
      serverId,
      token,
      clientMode: "managed-runner",
      secretSource: agentProxyTokenFile ? "agent-proxy-token-file" : "agent-proxy-token-env",
      activeCapabilities,
    };
  }

  const tokenFile = env.SLOCK_AGENT_TOKEN_FILE;
  const tokenLiteral = env.SLOCK_AGENT_TOKEN;
  if (tokenFile || tokenLiteral) {
    throw new AgentBootstrapError(
      "LEGACY_MACHINE_UNSUPPORTED",
      "SLOCK_AGENT_TOKEN_FILE/SLOCK_AGENT_TOKEN machine-token bootstrap is no longer supported by this CLI. Upgrade or restart the daemon so it injects SLOCK_AGENT_PROXY_URL plus SLOCK_AGENT_PROXY_TOKEN_FILE, or use RAFT_PROFILE with a credential from `raft agent login`.",
    );
  }

  throw new AgentBootstrapError(
    "MISSING_TOKEN",
    "Neither SLOCK_AGENT_PROXY_TOKEN_FILE nor SLOCK_AGENT_PROXY_TOKEN is set. The daemon should inject proxy credentials when spawning the agent process, or use RAFT_PROFILE with a credential from `raft agent login`.",
  );
}
