// `raft task claim --target <ch> [--number N ...] [--message-id <id> ...]`
// → POST /internal/agent-api/tasks/claim
//
// Either --number (task number) or --message-id (short or full) — at
// least one is required. Each instance of a flag can be repeated to
// claim several tasks in one call.

import type { Command } from "commander";
import { type AgentApiTaskClaimBody, type AgentApiTaskClaimSuccessResponse, TASK_CLAIM_REASON_ALREADY_CLAIMED_BY_YOU } from "@botiverse/raft-shared";

import { createAgentApiSurfaceClient } from "../../agentApiPath.js";
import { defineCommand, registerCliCommand } from "../../core/command.js";
import type { CommandRuntimeOptions } from "../../core/context.js";
import { cliError } from "../../core/errors.js";
import { writeText, adoptCliReplyText } from "../../core/renderer.js";
import { apiFailureError } from "../_apiFailure.js";
import { requireTargetAlias, type TargetAliasOpts } from "../_target.js";
import { formatFreshnessHoldOutput, isFreshnessHeldResponse } from "../freshness/_format.js";
import {
  reviewerIsolationEnabled,
  reviewerIsolationOption,
  type ReviewerIsolationOpts,
} from "../reviewerIsolation.js";
import { formatClaimResults } from "./_format.js";

interface ClaimOpts extends TargetAliasOpts, ReviewerIsolationOpts {
  number?: string[];
  messageId?: string[];
}

function isTaskClaimSuccessResponse(data: unknown): data is AgentApiTaskClaimSuccessResponse {
  return Boolean(data && typeof data === "object" && Array.isArray((data as { results?: unknown }).results));
}

export const taskClaimCommand = defineCommand(
  {
    name: "claim",
    description: "Claim one or more tasks (by task number or message id)",
    options: [
      { flags: "--target <target>", description: "Channel target: '#channel'" },
      { flags: "--channel <target>", description: "Legacy alias for --target (accepted during transition)" },
      {
        flags: "--number <n>",
        description: "Task number to claim (repeatable)",
        parse: (value, prev: string[] = []) => prev.concat(value),
      },
      {
        flags: "--message-id <id>",
        description: "Message id (full or short) to claim (repeatable)",
        parse: (value, prev: string[] = []) => prev.concat(value),
      },
      reviewerIsolationOption,
    ],
  },
  async (ctx, opts: ClaimOpts) => {
      const channel = requireTargetAlias(opts);
      const numbers = (opts.number ?? []).map((raw) => {
        const n = Number(raw);
        if (!Number.isFinite(n) || !Number.isInteger(n) || n <= 0) {
          throw cliError("INVALID_ARG", `--number must be a positive integer; got ${raw}`);
        }
        return n;
      });
      const messageIds = opts.messageId ?? [];

      if (numbers.length === 0 && messageIds.length === 0) {
        throw cliError("INVALID_ARG", "Provide at least one --number or --message-id");
      }

      const body: AgentApiTaskClaimBody = { channel };
      const reviewerIsolation = reviewerIsolationEnabled(opts, ctx.env);
      if (numbers.length > 0) body.task_numbers = numbers;
      if (messageIds.length > 0) body.message_ids = messageIds;
      if (reviewerIsolation) body.freshnessContextMode = "withheld";

      const agentContext = ctx.loadAgentContext();
      const client = ctx.createApiClient(agentContext);
      const agentApi = createAgentApiSurfaceClient(client);
      let res;
      try {
        res = await agentApi.tasks.claim(body);
      } catch (err) {
        if (reviewerIsolation) {
          throw cliError(
            "CLAIM_FAILED",
            "Reviewer-isolation task claim failed; upstream response detail was withheld.",
            { cause: err },
          );
        }
        throw err;
      }
      if (!res.ok) {
        if (reviewerIsolation) {
          const code = res.status >= 500 ? "SERVER_5XX" : "CLAIM_FAILED";
          throw cliError(
            code,
            `Reviewer-isolation task claim failed (HTTP ${res.status}); upstream error detail was withheld.`,
          );
        }
        if (res.status >= 500 && res.errorCode === "agent_proxy_failed") {
          throw apiFailureError(res, "CLAIM_FAILED", {
            suggestedNextAction:
              "This 5xx was generated by the local daemon proxy; use the correlation id to inspect daemon proxy transport logs before attributing it to the server.",
          });
        }
        const code = res.status >= 500 ? "SERVER_5XX" : "CLAIM_FAILED";
        throw cliError(code, res.error ?? `HTTP ${res.status}`);
      }
      if (!res.data) {
        throw cliError("INVALID_JSON_RESPONSE", "Agent API taskClaim returned an empty response body");
      }
      if (isFreshnessHeldResponse(res.data)) {
        writeText(ctx.io, formatFreshnessHoldOutput(channel, res.data, {
          heldAction: "Your task claim was not applied.",
          withholdContext: reviewerIsolation || res.data.freshnessContextMode === "withheld",
          draftInstructions: reviewerIsolation || res.data.freshnessContextMode === "withheld"
            ? "Retry remains held while reviewer isolation is active. Use a clean review target, or leave the seat and read only with explicit review authority.\n"
            : "After reviewing the newer context, rerun the task claim command if it is still correct.\n",
        }));
        return;
      }
      if (!isTaskClaimSuccessResponse(res.data)) {
        throw cliError("INVALID_JSON_RESPONSE", "Agent API taskClaim returned an unexpected response body");
      }
      writeText(ctx.io, adoptCliReplyText(formatClaimResults(channel, res.data) + "\n"));

      // A claim that succeeded for nothing must not exit 0. `claim` carries a
      // batch payload, so per-item refusals come back inside a 200 body and
      // never reach the `cliError` paths above — meaning `raft task claim && …`
      // used to run its right-hand side after every item was refused, while
      // unclaim/update/assign/unassign/convert/delete all exit non-zero on
      // failure. Deliberately keyed on ZERO successes, not "any failure": a
      // partial claim did do work, and reporting that as failure would make the
      // caller re-drive tasks it already holds. The thrown error repeats only a
      // one-line-per-refusal summary; the per-row payload above stays the
      // authoritative account of what happened.
      // "already claimed by you" is carried as a refusal (taskService returns a
      // reason string, so `success` is false), but it answers the only question
      // this exit status exists to answer — may I work on this task? — with
      // yes. Re-confirming a claim you already hold is behaviour the product
      // deliberately supports, so it must not read as failure: the prompt tells
      // agents not to start work when a claim fails, which would stop an agent
      // working on its own task.
      const authorisesWork = (r: { success: boolean; reason?: string | null }) =>
        r.success || r.reason === TASK_CLAIM_REASON_ALREADY_CLAIMED_BY_YOU;
      // No `length > 0` guard. An empty result set is the shape that most literally means
      // "nothing was claimed", so guarding it would exit 0 on exactly the case this exit code
      // exists for (@Maggie, #6549 review). NOT a behaviour fix: the empty-results response is
      // unreachable from this command — the input check above rejects a request with no numbers
      // and no message ids, so `results` cannot come back empty. Verified by trying to write a
      // test for it: the attempt only ever reaches the input guard. Removed because the guard
      // asserted something the invariant contradicts, not because it was live.
      if (!res.data.results.some(authorisesWork)) {
        // Typed, self-sufficient stderr. The bare `CliExit(1)` this replaces
        // relied on the stdout account above surviving to the reader — but a
        // batched invocation (`raft task claim … && raft message send …`) or a
        // harness that surfaces only stderr on non-zero exit loses stdout
        // entirely, leaving "Code: INTERNAL_BUG" as the whole story (task #60,
        // three cross-seat specimens). The error therefore repeats the one
        // decision-relevant line per refusal: who holds the lock, or why the
        // claim was refused. The stdout account above stays the full record.
        const conflicts = res.data.results.filter((r) => !authorisesWork(r));
        const anyLock = conflicts.some((r) => r.conflict?.kind === "claim_conflict");
        const summary = conflicts
          .map((r) => {
            const label = r.taskNumber ? `#${r.taskNumber}` : `msg:${r.messageId}`;
            const holder = r.conflict?.kind === "claim_conflict" && r.conflict.currentAssignee?.name
              ? `held by @${r.conflict.currentAssignee.name}`
              : (r.reason || "refused");
            return `${label} ${holder}`;
          })
          .join("; ");
        throw cliError(
          anyLock ? "CLAIM_CONFLICT" : "CLAIM_FAILED",
          `Claim refused — ${summary}. This is a concurrency lock or refusal, not a tool error and not a ruling on lane ownership.`,
          {
            suggestedNextAction:
              "Do not retry the identical claim and do not start conflicting execution. If you are this lane's canonical owner, correct the routing in the original thread.",
          },
        );
      }
  },
);

export function registerTaskClaimCommand(parent: Command, runtimeOptions: CommandRuntimeOptions = {}): void {
  registerCliCommand(parent, taskClaimCommand, runtimeOptions);
}
