export const announcementCatalog = {
  en: {
    language: "Admin language",
    announcements: "Announcements",
    newDraft: "New draft",
    loading: "Loading",
    noAnnouncements: "No announcements yet.",
    untitled: "Untitled",
    announcementDetail: "Announcement detail",
    newAnnouncement: "New announcement",
    authorityNote: "Content is global. Locale resolution, lifecycle, audit, and user dismiss receipts remain in Raft core.",
    draftSaved: "Draft saved.",
    draftCreated: "Draft created.",
    scheduleUpdated: "Schedule updated.",
    publishSucceeded: "Announcement published.",
    cancelSucceeded: "Schedule cancelled. Announcement returned to draft.",
    expireSucceeded: "Announcement expired.",
    loadFailed: "Failed to load announcements.",
    saveFailed: "Save failed.",
    actionFailed: (action: string) => `${action} failed.`,
    confirmPublish: "Publish this announcement? Its time window must not overlap another published announcement.",
    confirmCancel: "Cancel this schedule and return the announcement to draft?",
    confirmExpire: "Expire this announcement now? It will never reappear.",
    saveDraft: "Save draft",
    createDraft: "Create draft",
    updateSchedule: "Update schedule",
    publish: "Publish",
    cancelSchedule: "Cancel schedule",
    expireNow: "Expire now",
    locales: "Locales",
    localeHelp: "Every selected locale must be complete before publish.",
    defaultLocale: "Default",
    content: (locale: string) => `Content · ${locale}`,
    markdownHelp: "Markdown is rendered live with the user-modal contract.",
    addPage: "Page",
    announcementTitle: "Announcement title",
    announcementTitlePlaceholder: "Announcement title",
    page: (index: number) => `Page ${index}`,
    removePage: "Remove page across all locales",
    optionalPageTitle: "Optional page title",
    markdownBody: "Markdown body",
    visibilityWindow: "Visibility window",
    startTime: "Start time · blank = publish now",
    endTime: "End time · optional",
    windowHelp: "Published windows cannot overlap. A scheduled start is discovered on the user's next app entry; it does not interrupt an already-open tab.",
    livePreview: (locale: string) => `Live preview · ${locale}`,
    previewPlaceholder: "Preview updates as you type.",
    back: "Back",
    next: "Next",
    ok: "OK",
    auditTimeline: "Audit timeline",
    noAudit: "No audit events.",
    system: "system",
    status: {
      draft: "draft",
      scheduled: "scheduled",
      published: "published",
      expired: "expired",
    },
    auditAction: {
      created: "created",
      updated: "updated",
      published: "published",
      scheduled: "scheduled",
      schedule_updated: "schedule updated",
      schedule_cancelled: "schedule cancelled",
      activated: "activated",
      expired: "expired",
    },
    invalidDefault: "Default locale must be selected.",
    invalidLocales: "Select at least one locale.",
    invalidPageCount: "Announcements require 1–20 pages.",
    invalidTitle: (locale: string) => `${locale}: announcement title is required.`,
    invalidPageShape: "All locales must use the same page count.",
    invalidBody: (locale: string, page: number) => `${locale}: page ${page} body is required.`,
    invalidStart: "Start time is invalid.",
    invalidEnd: "End time is invalid.",
    invalidWindow: "End time must be later than start time.",
  },
  "zh-cn": {
    language: "管理界面语言",
    announcements: "公告",
    newDraft: "新建草稿",
    loading: "加载中",
    noAnnouncements: "暂无公告。",
    untitled: "未命名",
    announcementDetail: "公告详情",
    newAnnouncement: "新公告",
    authorityNote: "内容面向全局用户。语言解析、生命周期、审计和用户关闭回执均由 Raft core 负责。",
    draftSaved: "草稿已保存。",
    draftCreated: "草稿已创建。",
    scheduleUpdated: "排期已更新。",
    publishSucceeded: "公告已发布。",
    cancelSucceeded: "排期已取消，公告已退回草稿。",
    expireSucceeded: "公告已立即失效。",
    loadFailed: "公告加载失败。",
    saveFailed: "保存失败。",
    actionFailed: (action: string) => `${action}失败。`,
    confirmPublish: "确认发布此公告？它的时间窗口不能与其他已发布公告重叠。",
    confirmCancel: "确认取消排期并将公告退回草稿？",
    confirmExpire: "确认让此公告立即失效？失效后不会再次出现。",
    saveDraft: "保存草稿",
    createDraft: "创建草稿",
    updateSchedule: "更新排期",
    publish: "发布",
    cancelSchedule: "取消排期",
    expireNow: "立即失效",
    locales: "内容语言",
    localeHelp: "发布前，每个已选语言都必须填写完整。",
    defaultLocale: "默认语言",
    content: (locale: string) => `内容 · ${locale}`,
    markdownHelp: "Markdown 预览与用户公告弹窗使用同一渲染契约。",
    addPage: "新增页",
    announcementTitle: "公告标题",
    announcementTitlePlaceholder: "公告标题",
    page: (index: number) => `第 ${index} 页`,
    removePage: "在所有语言中删除此页",
    optionalPageTitle: "可选页标题",
    markdownBody: "Markdown 正文",
    visibilityWindow: "展示时间窗",
    startTime: "开始时间 · 留空表示立即发布",
    endTime: "结束时间 · 可选",
    windowHelp: "已发布公告的时间窗不能重叠。排期开始时不会打断已打开的页面；用户下次进入应用时才会看到。",
    livePreview: (locale: string) => `实时预览 · ${locale}`,
    previewPlaceholder: "输入内容时，预览会实时更新。",
    back: "上一页",
    next: "下一页",
    ok: "知道了",
    auditTimeline: "审计时间线",
    noAudit: "暂无审计事件。",
    system: "系统",
    status: {
      draft: "草稿",
      scheduled: "已排期",
      published: "展示中",
      expired: "已失效",
    },
    auditAction: {
      created: "已创建",
      updated: "草稿已更新",
      published: "已发布",
      scheduled: "已排期",
      schedule_updated: "排期已更新",
      schedule_cancelled: "排期已取消",
      activated: "已生效",
      expired: "已失效",
    },
    invalidDefault: "必须选择默认语言。",
    invalidLocales: "请至少选择一种语言。",
    invalidPageCount: "公告必须包含 1–20 页。",
    invalidTitle: (locale: string) => `${locale}：请填写公告标题。`,
    invalidPageShape: "所有语言必须使用相同的页数和顺序。",
    invalidBody: (locale: string, page: number) => `${locale}：请填写第 ${page} 页正文。`,
    invalidStart: "开始时间无效。",
    invalidEnd: "结束时间无效。",
    invalidWindow: "结束时间必须晚于开始时间。",
  },
} as const;

export type AnnouncementUiLocale = keyof typeof announcementCatalog;
